### ISSUE TITLE
Dropdown options of ellipsis icon in header example not aligning 

### ISSUE THREAD

**Issue by tracybarmore** [grommet/grommet-docs#129] opened 2016-10-03 22:59 UTC
In [Title, inline menu, and search] header example, on click of ellipsis icon, options aren't aligned with the original ellipsis icon. 

https://grommet.github.io/hpe/docs/header/examples#1
### Your Environment
- Browser Name and version: Firefox 48.0 and Chrome 53.0.2785.116

![screen shot 2016-10-03 at 3 34 06 pm](https://cloud.githubusercontent.com/assets/13038855/19056563/e2f2d168-897e-11e6-9759-af830c77d864.png)

**Comment by bryanjacquot** [comment] 2016-10-07 18:06
This is related to #130.

**Comment by epilande** [comment] 2016-10-11 11:23
Not able to reproduce the issue. Fixed in latest grommet.

**Closed as completed by epilande** 2016-10-11 11:23 UTC
