### ISSUE TITLE
List of the type of charts on the example code page for Charts component is not working as expected

### ISSUE THREAD

**Issue by ghoshabhi** [grommet/grommet-docs#223] opened 2017-01-14 00:09 UTC
When going to the [example code page](https://grommet.github.io/docs/chart/examples) for the Charts component is not working as expected. On selecting the type of Graph as `Line` or `Area` the list component scrolls automatically which gives a feeling that something has changed. 

### Expected Behavior
The list should not move on selecting different type of a Chart.

### Actual Behavior
When toggling the `Line` or `Area` type of chart, the list moves in a jiffy giving a feeling that something changed on the screen when nothing changes.

### URL or screen shot exhibiting the issue
http://g.recordit.co/hForAlA9xh.gif

### Steps to Reproduce
 1. Go to the Chart component examples page
 2. Toggle "Bar" a few times
 3. Toggle "Line" or "Area"

### Your Environment
* Google Chrome Version 55.0.2883.95 (64-bit)
* macOS Sierra 10.12.2

**Comment by ericsoderberghp** [comment] 2017-01-18 18:03
We could use Animate inside the InteractiveExample PropFields to be more graceful.

**Comment by tracybarmore** [comment] 2017-05-01 16:39
Hi @ghoshabhi, we've made a lot of changes to grommet-docs over the last few months and believe somewhere along the way, we have fixed this issue. 

Since I'm not able to replicate it any longer, I'm going to close this issue. If you still have questions or are able to reproduce the problem, please feel free to reopen. Thanks!

**Closed as completed** 2017-05-01 16:39 UTC

**Comment by ghoshabhi** [comment] 2017-05-01 17:28
@tracybarmore : Everything looks good now. The prop side bar still moves on toggling certain props, but then I found out that it was because the toggling added and removed certain props to the list and that is why the link grows and shrinks. 

Thank you very much!
